"""Pass 4: a push-capable driver contract, and mutual TLS.

README items 3 and 4. Writes docs/SUBSCRIPTIONS_AND_TLS.md and out/pass4.json.
"""
from __future__ import annotations

import asyncio
import json
import pathlib
import sys
import tempfile
import time

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent / "src"))

import mtls                       # noqa: E402
import subscribe as S             # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent
OUT = ROOT / "out"
DOCS = ROOT / "docs"


def report(d: dict) -> str:
    L: list[str] = []
    A = L.append
    w, c, m, ctl = d["writes"], d["compare"], d["matrix"], d["control"]

    A("# A driver contract that models subscriptions, and mutual TLS\n")
    A(f"The last two items on this project's not-built list. Generated by "
      f"`run_pass4.py` in {d['elapsed_s']:.0f} s.\n")

    A("## 1. Telling \"no change\" from \"no answer\"\n")
    A("The OPC-UA leg found the problem in pass 3 and the README stated the "
      "diagnosis correctly: *a collector that reads \"no data\" as \"device "
      "down\" will declare a healthy machine dead the moment its temperature "
      "stops moving — which on an idle machine is most of the weekend.* The fix "
      "is not a bigger poll. It is a contract where one fetch answers two "
      "questions that a poll could only answer together:\n")
    A("| | |\n|---|---|")
    A("| **what the device said** | zero or more readings, each with its own quality |")
    A("| **whether the device is there** | liveness, from *contact* — never from whether a value moved |")
    A("\nA polled device answers both at once, because a poll that returns data "
      "proves contact. A subscribed device does not, and that is the whole "
      "difference. So the subscription carries a **keep-alive**: the publisher "
      "promises to send something every interval, an empty publish if it has no "
      "news, and silence past the deadline is the only evidence of death either "
      "transport can offer.\n")

    A("\n### The original finding, now measured under both contracts\n")
    A(f"One initial publish, then {w['n_writes']} writes of which one repeats "
      f"the previous value:\n")
    A("| write | device published? | readings | liveness | old contract | new contract |")
    A("|---:|:--:|---:|---|---|---|")
    for r in w["writes"]:
        A(f"| {r['wrote']:.1f} | {'yes' if r['device_published'] else '**no**'} | "
          f"{r['n_readings']} | {r['liveness']} | "
          f"{'**DOWN**' if r['old_contract'] == 'DOWN' else 'UP'} | "
          f"{r['new_contract']} |")
    A(f"\n{w['n_writes']} writes produced {w['n_notifications']} notifications, "
      "because OPC-UA publishes on *change* and one write changed nothing. On "
      "that tick the old contract calls a working device dead, and the new one "
      "reports `KEEPALIVE` — the device answered, on time, with nothing to say.\n")

    A("\n### And on an idle machine, which is the case that matters\n")
    A(f"A device that is healthy and simply has no news, sampled "
      f"{c['ticks']} times over {c['steady_s']:.1f} s:\n")
    A(f"- old contract: **{c['old_contract_false_down']} of {c['ticks']} ticks "
      f"call it DOWN** ({c['old_contract_false_down_frac'] * 100:.0f}%)")
    A(f"- new contract: **{c['new_contract_false_down']}**, with "
      f"{c['keepalives_seen']} keep-alives seen")
    A(f"\nThen the device really dies. The new contract notices in "
      f"**{c['detection_s']:.2f} s** against its own deadline of "
      f"{c['deadline_s']:.1f} s — {c['keepalive_s']:.1f} s keep-alive × "
      f"({c['missed_allowed']} missed allowed + 1). The deadline is deliberately "
      "not the interval: setting them equal declares a device dead on the first "
      "late packet, which is the original bug wearing a new name.\n")
    A("**Liveness is three-valued because the useful state is the middle one.** "
      "Collapsing `KEEPALIVE` into `FRESH` throws away how old the newest value "
      "is; collapsing it into `SILENT` is the bug. And `PolledAdapter` — which "
      "wraps every existing driver unchanged — never reports `KEEPALIVE`, "
      "because a polled transport provides no liveness signal and manufacturing "
      "one would be the same lie in the other direction.\n")

    A("\n## 2. Mutual TLS\n")
    A("Loopback is not a boundary; it is the absence of one that happens to be "
      "hard to reach. Ordinary TLS answers *is this the server I meant to talk "
      "to*. On a plant network the question that matters more is the other one: "
      "*is this gateway one of ours* — and a collector that verifies the uplink "
      "and then sends to it has protected the data in flight and authenticated "
      "nobody.\n")
    A(f"\nOne CA, one server certificate, three client certificates and a rogue "
      f"CA, all minted in-process per run. TLS "
      f"{next((r['tls_version'] for r in m['rows'] if r['tls_version']), '1.3')}, "
      f"{next((r['cipher'] for r in m['rows'] if r['cipher']), '')}, with 1.2 "
      "and below refused rather than deprecated.\n")
    A("\n| case | expected | result |")
    A("|---|---|---|")
    for r in m["rows"]:
        got = "accepted" if r["accepted"] else f"refused — `{r['kind']}`"
        A(f"| {r['case']} | {r['expected']} | {got} |")
    A(f"\nThe accepted connection is identified as "
      f"**`{m['accepted_peer_cns'][0]}`** — from the certificate, not from the "
      "payload. A gateway id in the message body is a claim; a gateway id in the "
      "peer certificate is established before the first byte of body is read.\n")

    A("\n### Why the refusals are the result and the acceptance is not\n")
    A("Showing that a valid client connects proves almost nothing, because a "
      "server with verification switched off passes that test too. The control "
      "runs the same clients against a `CERT_NONE` server:\n")
    A(f"- accepts a client with **no certificate**: `{ctl['accepts_anonymous']}`")
    A(f"- accepts a client signed by a **different CA**: `{ctl['accepts_rogue']}`")
    A(f"- peer common names seen: `{ctl['peer_cns']}`\n")
    A("Both connections succeed and neither has an identity. That is what a "
      "happy-path TLS test cannot distinguish from the real thing.\n")

    A("\n### What this still is not\n")
    A("No CA infrastructure: no revocation, no OCSP, no renewal, no HSM, and the "
      "CA private key lives in the same process as everything it signs. IEC "
      "62443 SL-2 wants a managed identity lifecycle, and this demonstrates that "
      "the transport can carry and enforce identities — not that anybody is "
      "managing them. `docs/SECURITY_62443.md` §5 is updated rather than "
      "retired. Certificates are generated per run and never written to the "
      "repository, which a test asserts: a repository with a private key in its "
      "history has one forever.\n")
    return "\n".join(L) + "\n"


def main() -> None:
    t0 = time.time()
    OUT.mkdir(exist_ok=True)
    DOCS.mkdir(exist_ok=True)
    d = {
        "writes": asyncio.run(S.write_repeat_experiment()),
        "compare": asyncio.run(S.compare_contracts()),
    }
    print("  subscription contract done")
    with tempfile.TemporaryDirectory() as td:
        d["matrix"] = mtls.refusal_matrix(pathlib.Path(td) / "a")
        d["control"] = mtls.unauthenticated_server_check(pathlib.Path(td) / "b")
    print("  mTLS done")
    d["elapsed_s"] = time.time() - t0
    (OUT / "pass4.json").write_text(json.dumps(d, indent=2, default=str),
                                    encoding="utf-8")
    (DOCS / "SUBSCRIPTIONS_AND_TLS.md").write_text(report(d), encoding="utf-8")
    print(f"wrote docs/SUBSCRIPTIONS_AND_TLS.md in {d['elapsed_s']:.0f}s")


if __name__ == "__main__":
    main()
